# Generated by Django 4.2.2 on 2023-07-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(default='', max_length=10)),
                ('password', models.CharField(max_length=1000)),
            ],
        ),
    ]
