# Generated by Django 4.2.2 on 2023-07-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('author', models.CharField(max_length=30, unique=True)),
                ('video_embed', models.CharField(default=None, max_length=1000)),
                ('text', models.TextField(unique=True)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
