# Generated by Django 4.2.4 on 2024-05-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='background',
            field=models.CharField(max_length=1000000000),
        ),
        migrations.AlterField(
            model_name='application',
            name='example',
            field=models.CharField(max_length=1000000000),
        ),
        migrations.AlterField(
            model_name='application',
            name='motivation',
            field=models.CharField(max_length=1000000000),
        ),
    ]
