# Generated by Django 4.2.2 on 2023-07-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'User'), (2, 'Admin')], default=1),
        ),
    ]
