# Generated by Django 4.2.4 on 2023-09-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True)),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.TextField(unique=True)),
            ],
        ),
    ]
