# Generated by Django 4.2.4 on 2024-05-20 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.CharField(max_length=1000000000, unique=True)),
                ('background', models.CharField(max_length=1000000000, unique=True)),
                ('example', models.CharField(max_length=1000000000, unique=True)),
                ('taken_by', models.CharField(default='', max_length=90)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.user')),
            ],
        ),
    ]
