# Generated by Django 4.2.4 on 2024-05-20 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_application_background_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='taken_by',
        ),
        migrations.AddField(
            model_name='application',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
